/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MapContainer: typeof import('./src/components/MapContainer.vue')['default']
    Right: typeof import('./src/components/right.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test.vue')['default']
    ToTop: typeof import('./src/components/toTop.vue')['default']
    WebTop: typeof import('./src/components/webTop.vue')['default']
  }
}
